### ISSUE TITLE
ButtonGroup and Divider

### ISSUE THREAD

**Issue by cecton** [cecton/yewprint#2]
Source: https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/core-examples/buttonGroupExample.tsx
Doc: https://blueprintjs.com/docs/#core/components/button-group

Source: https://github.com/palantir/blueprint/blob/841b2e12/packages/core/src/components/divider/divider.tsx
Doc: https://blueprintjs.com/docs/#core/components/divider

This should be an easy task as they're just purely visual components.

At the moment there is no handling for the class prefix (`bp3-`), we can just hardcode it until we find a better option. There is also no handling for letting the user decide if the element should be a div or something else (property tagName) so you can just hardcode to the default.

Please let me know you start working on it to avoid having multiple people working on the same component.

Yew tutorial: https://dev.to/davidedelpapa/yew-tutorial-01-introduction-13ce
Yew reference manual: https://yew.rs/docs/en/intro/
Similar to: https://github.com/cecton/yewprint/blob/main/src/buttons.rs
Available CSS classes: https://github.com/palantir/blueprint/blob/develop/packages/core/src/common/classes.ts

**Comment by EstebanBorai** [comment]
Hello @cecton !

I would like to participate on this issue!
