### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by cecton** [cecton/yewprint#21]
Source: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/text/text.tsx
Doc: https://blueprintjs.com/docs/#core/components/text

This should be an easy task as this is just a purely visual component.

At the moment there is no handling for the class prefix (bp3-), we can just hardcode it until we find a better option. There is also no handling for letting the user decide if the element should be a div or something else (property tagName) so you can just hardcode to the default.

Please let me know you start working on it to avoid having multiple people working on the same component.

Yew tutorial: https://dev.to/davidedelpapa/yew-tutorial-01-introduction-13ce
Yew reference manual: https://yew.rs/docs/en/intro/
Similar to: https://github.com/cecton/yewprint/blob/main/src/buttons.rs
Available CSS classes: https://github.com/palantir/blueprint/blob/develop/packages/core/src/common/classes.ts

**Comment by oScape** [comment]
I think it might be a good first issue for me :) If it's ok for you, I will work on it.
