### ISSUE TITLE
Card & Elevation

### ISSUE THREAD

**Issue by cecton** [cecton/yewprint#3]
Source: https://github.com/palantir/blueprint/blob/841b2e12/packages/core/src/components/card/card.tsx#L23
Doc: https://blueprintjs.com/docs/#core/components/card

Source: https://github.com/palantir/blueprint/blob/841b2e12fec1970704b754f7794c683c735d0439/packages/core/src/common/elevation.ts
Doc: https://blueprintjs.com/docs/#core/variables.elevation-drop-shadows

This should be an easy task as this is just a purely visual component. The elevation is an enum (no need for the numeric value in Rust).

At the moment there is no handling for the class prefix (bp3-), we can just hardcode it until we find a better option.

Please let me know you start working on it to avoid having multiple people working on the same component.

Yew tutorial: https://dev.to/davidedelpapa/yew-tutorial-01-introduction-13ce
Yew reference manual: https://yew.rs/docs/en/intro/
Similar to: https://github.com/cecton/yewprint/blob/main/src/buttons.rs
Available CSS classes: https://github.com/palantir/blueprint/blob/develop/packages/core/src/common/classes.ts

**Comment by rbeard0330** [comment]
I can work on this one.
