### ISSUE TITLE
Completion of `Button` and `Icon`

### ISSUE THREAD

**Issue by nbrr** [cecton/yewprint#46]
Rendering for `Tag` is a bit messy at the moment because `Button` and `Icon` are a bit lacking.
![image](https://user-images.githubusercontent.com/21319620/95516495-9e0d3000-09bf-11eb-8bdb-3aba6e1ccd42.png)
Some classes are missing. `Icon` looks troublesome because they are handled by a macro.
See relevant [page](https://blueprintjs.com/docs/#core/components/tag) in blueprint's doc. The remove buttons on tags don't have `bp3-button` class and cross icons are wrapped in a span with class `bp3-icon-small-cross` so I imagine each icon has its own class.

**Comment by cecton** [comment]
https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/tag/tag.tsx#L152-L159

I think the problem is that you used the `<Button>` component of yewprint instead of the `<button>` html component.

See in the code here they don't use blueprint's <Button> either
