### ISSUE TITLE
Use HtmlSelect instead of Menu for Intent in examples

### ISSUE THREAD

**Issue by cecton** [cecton/yewprint#49]
This is a task just for you :slightly_smiling_face: @Yozhgoor 

A good picture is better than a long explanation.

Instead of having this:

![image](https://user-images.githubusercontent.com/3018448/95622306-7c6d8080-0a73-11eb-9f92-a232f84c2d2e.png)

I want this:

![image](https://user-images.githubusercontent.com/3018448/95622384-af177900-0a73-11eb-9911-ee82d67b7b46.png)

In all examples everywhere.

**Comment by Yozhgoor** [comment]
am in
